---

- name: Cisco show version
  hosts: switches
  gather_facts: false
  connection: ansible.netcommon.network_cli

  tasks:
    - name: run show version on the routers
      cisco.ios.ios_command:
        commands: 
          - show version | i Version
      register: output

    - name: print output
      debug:
        var: output.stdout_lines